server:
  port: 8011
spring:
  application:
    name: nacos09_01
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: nacos09
